steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/a2a-repo/agent-node', '-f', 'apps/agent-node/Dockerfile', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/a2a-repo/agent-node']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'a2a-agent-node'
      - '--image'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/a2a-repo/agent-node'
      - '--set-secrets=TREASURY_ADDRESS=treasury-address:latest,AGENT_SECRET_KEY=agent-secret-key:latest,AIRDROP_PRIVATE_KEY=AIRDROP_PRIVATE_KEY:latest,DB_PASSWORD=DB_PASSWORD:latest'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--set-env-vars=DB_USER=agent_user,DB_NAME=agent_db,INSTANCE_CONNECTION_NAME=a2a-project-486504:asia-northeast1:a2a-agent-db,AIRDROP_TOKEN_ADDRESS=0xE0Bf7CE4379E88768A8515E126Abf61C2C7b2Cf2'
      - '--add-cloudsql-instances=a2a-project-486504:asia-northeast1:a2a-agent-db'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'

  # Build the Paymaster container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/a2a-repo/a2a-paymaster', '-f', 'apps/paymaster/Dockerfile', '.']

  # Push the Paymaster container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/a2a-repo/a2a-paymaster']

  # Deploy Paymaster container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'a2a-paymaster'
      - '--image'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/a2a-repo/a2a-paymaster'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=a2a-project-486504:asia-northeast3:a2a-paymaster-db'
      - '--set-env-vars=RPC_URL=https://mainnet.base.org,MARKUP_RATE=0.12,DB_USER=paymaster_admin,DB_NAME=paymaster_db,INSTANCE_CONNECTION_NAME=a2a-project-486504:asia-northeast3:a2a-paymaster-db'
      - '--set-secrets=A2A_PAYMASTER_API_KEY=A2A_PAYMASTER_API_KEY:latest,UPSTREAM_PAYMASTER_URL=UPSTREAM_PAYMASTER_URL:latest,TREASURY_ADDRESS=TREASURY_ADDRESS:latest,DB_PASS=DB_PASSWORD:latest'

images:
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/a2a-repo/agent-node'
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/a2a-repo/a2a-paymaster'

options:
  logging: CLOUD_LOGGING_ONLY
