export { IdentityManager } from './identity/did-manager'
export type { EphemeralIdentity } from './identity/did-manager'
export { VCHandler } from './credentials/vc-handler.service'
export { createResolver } from './resolver'
export type { ResolverOptions } from './resolver'
